# Generated by Django 4.1.7 on 2023-02-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_team_first_name_alter_team_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
